### ISSUE TITLE
glitch: pub always shows up with id as name

### ISSUE THREAD

**Issue by evbogue** [dominictarr/patchbay#46]
I haven't seen this happen to any other pub, but for some reason my pub always shows up as its' msg.key in Patchbay. I tried naming it a handful of times, and that didn't appear to help. 

Is this a bug in ssb-avatar or did I publish a whack message from my pub? Unclear.

In Patchwork my pub shows up with the self-assigned name: evbogue.com

![2016-07-20-114514_648x503_scrot](https://cloud.githubusercontent.com/assets/2468866/16995053/cd554650-4e6f-11e6-9632-444448c2a294.png)

**Comment by clehner** [comment]
it is probably because the name code looks for names in mentions first, and then falls back to looking for names in about messages. in this case it looks like there are only bare mentions of the pub so an empty name is picked. i think it would be better to combine results from both the mention and about messages. relevant code is in modules/names.js.

**Comment by evbogue** [comment]
@clehner You're right, this issue resolved when I talked at my pub.
